/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorIndexRouteImport } from './routes/vendor/index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as StatusSuccessRouteImport } from './routes/status/success'
import { Route as OrganizerSalesRouteImport } from './routes/organizer/sales'
import { Route as OrganizerLayoutRouteImport } from './routes/organizer/layout'
import { Route as OrganizerAttendeeRouteImport } from './routes/organizer/attendee'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AccountAddPayoutAccountRouteImport } from './routes/account/add-payout-account'
import { Route as OnboardingServiceVendorRouteImport } from './routes/Onboarding/service-vendor'
import { Route as OnboardingOnboardingRouteImport } from './routes/Onboarding/onboarding'
import { Route as OnboardingServicesRouteImport } from './routes/Onboarding/Services'
import { Route as VendorProposalIndexRouteImport } from './routes/vendor/proposal/index'
import { Route as VendorEventIndexRouteImport } from './routes/vendor/event/index'
import { Route as VendorProposalProposalIdRouteImport } from './routes/vendor/proposal/$proposalId'
import { Route as AuthPasswordOtpRouteImport } from './routes/auth/password/otp'
import { Route as AuthPasswordForgetRouteImport } from './routes/auth/password/forget'
import { Route as AuthOtpVerifyRouteImport } from './routes/auth/otp/verify'
import { Route as OnboardingVendorSubServicesTwoRouteImport } from './routes/Onboarding/vendor-sub-services/two'
import { Route as OnboardingVendorSubServicesThreeRouteImport } from './routes/Onboarding/vendor-sub-services/three'
import { Route as OnboardingSubServicesTwoRouteImport } from './routes/Onboarding/sub-services/two'
import { Route as OnboardingSubServicesThreeRouteImport } from './routes/Onboarding/sub-services/three'
import { Route as OnboardingSubServicesReviewRouteImport } from './routes/Onboarding/sub-services/review'
import { Route as OnboardingSubServicesOneRouteImport } from './routes/Onboarding/sub-services/one'
import { Route as OnboardingSubServicesFourRouteImport } from './routes/Onboarding/sub-services/four'
import { Route as OnboardingSubServicesFiveRouteImport } from './routes/Onboarding/sub-services/five'
import { Route as VendorEventEventIdIndexRouteImport } from './routes/vendor/event/$eventId/index'
import { Route as VendorEventEventIdProposalRouteImport } from './routes/vendor/event/$eventId/proposal'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorIndexRoute = VendorIndexRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/organizer/',
  path: '/organizer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusSuccessRoute = StatusSuccessRouteImport.update({
  id: '/status/success',
  path: '/status/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerSalesRoute = OrganizerSalesRouteImport.update({
  id: '/organizer/sales',
  path: '/organizer/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerLayoutRoute = OrganizerLayoutRouteImport.update({
  id: '/organizer/layout',
  path: '/organizer/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerAttendeeRoute = OrganizerAttendeeRouteImport.update({
  id: '/organizer/attendee',
  path: '/organizer/attendee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddPayoutAccountRoute = AccountAddPayoutAccountRouteImport.update({
  id: '/account/add-payout-account',
  path: '/account/add-payout-account',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingServiceVendorRoute = OnboardingServiceVendorRouteImport.update({
  id: '/Onboarding/service-vendor',
  path: '/Onboarding/service-vendor',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingOnboardingRoute = OnboardingOnboardingRouteImport.update({
  id: '/Onboarding/onboarding',
  path: '/Onboarding/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingServicesRoute = OnboardingServicesRouteImport.update({
  id: '/Onboarding/Services',
  path: '/Onboarding/Services',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProposalIndexRoute = VendorProposalIndexRouteImport.update({
  id: '/vendor/proposal/',
  path: '/vendor/proposal/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorEventIndexRoute = VendorEventIndexRouteImport.update({
  id: '/vendor/event/',
  path: '/vendor/event/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorProposalProposalIdRoute =
  VendorProposalProposalIdRouteImport.update({
    id: '/vendor/proposal/$proposalId',
    path: '/vendor/proposal/$proposalId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthPasswordOtpRoute = AuthPasswordOtpRouteImport.update({
  id: '/auth/password/otp',
  path: '/auth/password/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasswordForgetRoute = AuthPasswordForgetRouteImport.update({
  id: '/auth/password/forget',
  path: '/auth/password/forget',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpVerifyRoute = AuthOtpVerifyRouteImport.update({
  id: '/auth/otp/verify',
  path: '/auth/otp/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingVendorSubServicesTwoRoute =
  OnboardingVendorSubServicesTwoRouteImport.update({
    id: '/Onboarding/vendor-sub-services/two',
    path: '/Onboarding/vendor-sub-services/two',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingVendorSubServicesThreeRoute =
  OnboardingVendorSubServicesThreeRouteImport.update({
    id: '/Onboarding/vendor-sub-services/three',
    path: '/Onboarding/vendor-sub-services/three',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingSubServicesTwoRoute =
  OnboardingSubServicesTwoRouteImport.update({
    id: '/Onboarding/sub-services/two',
    path: '/Onboarding/sub-services/two',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingSubServicesThreeRoute =
  OnboardingSubServicesThreeRouteImport.update({
    id: '/Onboarding/sub-services/three',
    path: '/Onboarding/sub-services/three',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingSubServicesReviewRoute =
  OnboardingSubServicesReviewRouteImport.update({
    id: '/Onboarding/sub-services/review',
    path: '/Onboarding/sub-services/review',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingSubServicesOneRoute =
  OnboardingSubServicesOneRouteImport.update({
    id: '/Onboarding/sub-services/one',
    path: '/Onboarding/sub-services/one',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingSubServicesFourRoute =
  OnboardingSubServicesFourRouteImport.update({
    id: '/Onboarding/sub-services/four',
    path: '/Onboarding/sub-services/four',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingSubServicesFiveRoute =
  OnboardingSubServicesFiveRouteImport.update({
    id: '/Onboarding/sub-services/five',
    path: '/Onboarding/sub-services/five',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendorEventEventIdIndexRoute = VendorEventEventIdIndexRouteImport.update({
  id: '/vendor/event/$eventId/',
  path: '/vendor/event/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorEventEventIdProposalRoute =
  VendorEventEventIdProposalRouteImport.update({
    id: '/vendor/event/$eventId/proposal',
    path: '/vendor/event/$eventId/proposal',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/Onboarding/Services': typeof OnboardingServicesRoute
  '/Onboarding/onboarding': typeof OnboardingOnboardingRoute
  '/Onboarding/service-vendor': typeof OnboardingServiceVendorRoute
  '/account/add-payout-account': typeof AccountAddPayoutAccountRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/signin': typeof AuthSigninRoute
  '/organizer/attendee': typeof OrganizerAttendeeRoute
  '/organizer/layout': typeof OrganizerLayoutRoute
  '/organizer/sales': typeof OrganizerSalesRoute
  '/status/success': typeof StatusSuccessRoute
  '/account': typeof AccountIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/Onboarding/sub-services/five': typeof OnboardingSubServicesFiveRoute
  '/Onboarding/sub-services/four': typeof OnboardingSubServicesFourRoute
  '/Onboarding/sub-services/one': typeof OnboardingSubServicesOneRoute
  '/Onboarding/sub-services/review': typeof OnboardingSubServicesReviewRoute
  '/Onboarding/sub-services/three': typeof OnboardingSubServicesThreeRoute
  '/Onboarding/sub-services/two': typeof OnboardingSubServicesTwoRoute
  '/Onboarding/vendor-sub-services/three': typeof OnboardingVendorSubServicesThreeRoute
  '/Onboarding/vendor-sub-services/two': typeof OnboardingVendorSubServicesTwoRoute
  '/auth/otp/verify': typeof AuthOtpVerifyRoute
  '/auth/password/forget': typeof AuthPasswordForgetRoute
  '/auth/password/otp': typeof AuthPasswordOtpRoute
  '/vendor/proposal/$proposalId': typeof VendorProposalProposalIdRoute
  '/vendor/event': typeof VendorEventIndexRoute
  '/vendor/proposal': typeof VendorProposalIndexRoute
  '/vendor/event/$eventId/proposal': typeof VendorEventEventIdProposalRoute
  '/vendor/event/$eventId': typeof VendorEventEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/Onboarding/Services': typeof OnboardingServicesRoute
  '/Onboarding/onboarding': typeof OnboardingOnboardingRoute
  '/Onboarding/service-vendor': typeof OnboardingServiceVendorRoute
  '/account/add-payout-account': typeof AccountAddPayoutAccountRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/signin': typeof AuthSigninRoute
  '/organizer/attendee': typeof OrganizerAttendeeRoute
  '/organizer/layout': typeof OrganizerLayoutRoute
  '/organizer/sales': typeof OrganizerSalesRoute
  '/status/success': typeof StatusSuccessRoute
  '/account': typeof AccountIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/vendor': typeof VendorIndexRoute
  '/Onboarding/sub-services/five': typeof OnboardingSubServicesFiveRoute
  '/Onboarding/sub-services/four': typeof OnboardingSubServicesFourRoute
  '/Onboarding/sub-services/one': typeof OnboardingSubServicesOneRoute
  '/Onboarding/sub-services/review': typeof OnboardingSubServicesReviewRoute
  '/Onboarding/sub-services/three': typeof OnboardingSubServicesThreeRoute
  '/Onboarding/sub-services/two': typeof OnboardingSubServicesTwoRoute
  '/Onboarding/vendor-sub-services/three': typeof OnboardingVendorSubServicesThreeRoute
  '/Onboarding/vendor-sub-services/two': typeof OnboardingVendorSubServicesTwoRoute
  '/auth/otp/verify': typeof AuthOtpVerifyRoute
  '/auth/password/forget': typeof AuthPasswordForgetRoute
  '/auth/password/otp': typeof AuthPasswordOtpRoute
  '/vendor/proposal/$proposalId': typeof VendorProposalProposalIdRoute
  '/vendor/event': typeof VendorEventIndexRoute
  '/vendor/proposal': typeof VendorProposalIndexRoute
  '/vendor/event/$eventId/proposal': typeof VendorEventEventIdProposalRoute
  '/vendor/event/$eventId': typeof VendorEventEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/about': typeof AboutRoute
  '/Onboarding/Services': typeof OnboardingServicesRoute
  '/Onboarding/onboarding': typeof OnboardingOnboardingRoute
  '/Onboarding/service-vendor': typeof OnboardingServiceVendorRoute
  '/account/add-payout-account': typeof AccountAddPayoutAccountRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/signin': typeof AuthSigninRoute
  '/organizer/attendee': typeof OrganizerAttendeeRoute
  '/organizer/layout': typeof OrganizerLayoutRoute
  '/organizer/sales': typeof OrganizerSalesRoute
  '/status/success': typeof StatusSuccessRoute
  '/account/': typeof AccountIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/vendor/': typeof VendorIndexRoute
  '/Onboarding/sub-services/five': typeof OnboardingSubServicesFiveRoute
  '/Onboarding/sub-services/four': typeof OnboardingSubServicesFourRoute
  '/Onboarding/sub-services/one': typeof OnboardingSubServicesOneRoute
  '/Onboarding/sub-services/review': typeof OnboardingSubServicesReviewRoute
  '/Onboarding/sub-services/three': typeof OnboardingSubServicesThreeRoute
  '/Onboarding/sub-services/two': typeof OnboardingSubServicesTwoRoute
  '/Onboarding/vendor-sub-services/three': typeof OnboardingVendorSubServicesThreeRoute
  '/Onboarding/vendor-sub-services/two': typeof OnboardingVendorSubServicesTwoRoute
  '/auth/otp/verify': typeof AuthOtpVerifyRoute
  '/auth/password/forget': typeof AuthPasswordForgetRoute
  '/auth/password/otp': typeof AuthPasswordOtpRoute
  '/vendor/proposal/$proposalId': typeof VendorProposalProposalIdRoute
  '/vendor/event/': typeof VendorEventIndexRoute
  '/vendor/proposal/': typeof VendorProposalIndexRoute
  '/vendor/event/$eventId/proposal': typeof VendorEventEventIdProposalRoute
  '/vendor/event/$eventId/': typeof VendorEventEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/Onboarding/Services'
    | '/Onboarding/onboarding'
    | '/Onboarding/service-vendor'
    | '/account/add-payout-account'
    | '/auth/sign-up'
    | '/auth/signin'
    | '/organizer/attendee'
    | '/organizer/layout'
    | '/organizer/sales'
    | '/status/success'
    | '/account'
    | '/organizer'
    | '/vendor'
    | '/Onboarding/sub-services/five'
    | '/Onboarding/sub-services/four'
    | '/Onboarding/sub-services/one'
    | '/Onboarding/sub-services/review'
    | '/Onboarding/sub-services/three'
    | '/Onboarding/sub-services/two'
    | '/Onboarding/vendor-sub-services/three'
    | '/Onboarding/vendor-sub-services/two'
    | '/auth/otp/verify'
    | '/auth/password/forget'
    | '/auth/password/otp'
    | '/vendor/proposal/$proposalId'
    | '/vendor/event'
    | '/vendor/proposal'
    | '/vendor/event/$eventId/proposal'
    | '/vendor/event/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/Onboarding/Services'
    | '/Onboarding/onboarding'
    | '/Onboarding/service-vendor'
    | '/account/add-payout-account'
    | '/auth/sign-up'
    | '/auth/signin'
    | '/organizer/attendee'
    | '/organizer/layout'
    | '/organizer/sales'
    | '/status/success'
    | '/account'
    | '/organizer'
    | '/vendor'
    | '/Onboarding/sub-services/five'
    | '/Onboarding/sub-services/four'
    | '/Onboarding/sub-services/one'
    | '/Onboarding/sub-services/review'
    | '/Onboarding/sub-services/three'
    | '/Onboarding/sub-services/two'
    | '/Onboarding/vendor-sub-services/three'
    | '/Onboarding/vendor-sub-services/two'
    | '/auth/otp/verify'
    | '/auth/password/forget'
    | '/auth/password/otp'
    | '/vendor/proposal/$proposalId'
    | '/vendor/event'
    | '/vendor/proposal'
    | '/vendor/event/$eventId/proposal'
    | '/vendor/event/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/Onboarding/Services'
    | '/Onboarding/onboarding'
    | '/Onboarding/service-vendor'
    | '/account/add-payout-account'
    | '/auth/sign-up'
    | '/auth/signin'
    | '/organizer/attendee'
    | '/organizer/layout'
    | '/organizer/sales'
    | '/status/success'
    | '/account/'
    | '/organizer/'
    | '/vendor/'
    | '/Onboarding/sub-services/five'
    | '/Onboarding/sub-services/four'
    | '/Onboarding/sub-services/one'
    | '/Onboarding/sub-services/review'
    | '/Onboarding/sub-services/three'
    | '/Onboarding/sub-services/two'
    | '/Onboarding/vendor-sub-services/three'
    | '/Onboarding/vendor-sub-services/two'
    | '/auth/otp/verify'
    | '/auth/password/forget'
    | '/auth/password/otp'
    | '/vendor/proposal/$proposalId'
    | '/vendor/event/'
    | '/vendor/proposal/'
    | '/vendor/event/$eventId/proposal'
    | '/vendor/event/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
  AboutRoute: typeof AboutRoute
  OnboardingServicesRoute: typeof OnboardingServicesRoute
  OnboardingOnboardingRoute: typeof OnboardingOnboardingRoute
  OnboardingServiceVendorRoute: typeof OnboardingServiceVendorRoute
  AccountAddPayoutAccountRoute: typeof AccountAddPayoutAccountRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthSigninRoute: typeof AuthSigninRoute
  OrganizerAttendeeRoute: typeof OrganizerAttendeeRoute
  OrganizerLayoutRoute: typeof OrganizerLayoutRoute
  OrganizerSalesRoute: typeof OrganizerSalesRoute
  StatusSuccessRoute: typeof StatusSuccessRoute
  AccountIndexRoute: typeof AccountIndexRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  VendorIndexRoute: typeof VendorIndexRoute
  OnboardingSubServicesFiveRoute: typeof OnboardingSubServicesFiveRoute
  OnboardingSubServicesFourRoute: typeof OnboardingSubServicesFourRoute
  OnboardingSubServicesOneRoute: typeof OnboardingSubServicesOneRoute
  OnboardingSubServicesReviewRoute: typeof OnboardingSubServicesReviewRoute
  OnboardingSubServicesThreeRoute: typeof OnboardingSubServicesThreeRoute
  OnboardingSubServicesTwoRoute: typeof OnboardingSubServicesTwoRoute
  OnboardingVendorSubServicesThreeRoute: typeof OnboardingVendorSubServicesThreeRoute
  OnboardingVendorSubServicesTwoRoute: typeof OnboardingVendorSubServicesTwoRoute
  AuthOtpVerifyRoute: typeof AuthOtpVerifyRoute
  AuthPasswordForgetRoute: typeof AuthPasswordForgetRoute
  AuthPasswordOtpRoute: typeof AuthPasswordOtpRoute
  VendorProposalProposalIdRoute: typeof VendorProposalProposalIdRoute
  VendorEventIndexRoute: typeof VendorEventIndexRoute
  VendorProposalIndexRoute: typeof VendorProposalIndexRoute
  VendorEventEventIdProposalRoute: typeof VendorEventEventIdProposalRoute
  VendorEventEventIdIndexRoute: typeof VendorEventEventIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/': {
      id: '/vendor/'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof VendorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status/success': {
      id: '/status/success'
      path: '/status/success'
      fullPath: '/status/success'
      preLoaderRoute: typeof StatusSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/sales': {
      id: '/organizer/sales'
      path: '/organizer/sales'
      fullPath: '/organizer/sales'
      preLoaderRoute: typeof OrganizerSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/layout': {
      id: '/organizer/layout'
      path: '/organizer/layout'
      fullPath: '/organizer/layout'
      preLoaderRoute: typeof OrganizerLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/attendee': {
      id: '/organizer/attendee'
      path: '/organizer/attendee'
      fullPath: '/organizer/attendee'
      preLoaderRoute: typeof OrganizerAttendeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/add-payout-account': {
      id: '/account/add-payout-account'
      path: '/account/add-payout-account'
      fullPath: '/account/add-payout-account'
      preLoaderRoute: typeof AccountAddPayoutAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Onboarding/service-vendor': {
      id: '/Onboarding/service-vendor'
      path: '/Onboarding/service-vendor'
      fullPath: '/Onboarding/service-vendor'
      preLoaderRoute: typeof OnboardingServiceVendorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Onboarding/onboarding': {
      id: '/Onboarding/onboarding'
      path: '/Onboarding/onboarding'
      fullPath: '/Onboarding/onboarding'
      preLoaderRoute: typeof OnboardingOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Onboarding/Services': {
      id: '/Onboarding/Services'
      path: '/Onboarding/Services'
      fullPath: '/Onboarding/Services'
      preLoaderRoute: typeof OnboardingServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/proposal/': {
      id: '/vendor/proposal/'
      path: '/vendor/proposal'
      fullPath: '/vendor/proposal'
      preLoaderRoute: typeof VendorProposalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/event/': {
      id: '/vendor/event/'
      path: '/vendor/event'
      fullPath: '/vendor/event'
      preLoaderRoute: typeof VendorEventIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/proposal/$proposalId': {
      id: '/vendor/proposal/$proposalId'
      path: '/vendor/proposal/$proposalId'
      fullPath: '/vendor/proposal/$proposalId'
      preLoaderRoute: typeof VendorProposalProposalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password/otp': {
      id: '/auth/password/otp'
      path: '/auth/password/otp'
      fullPath: '/auth/password/otp'
      preLoaderRoute: typeof AuthPasswordOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/password/forget': {
      id: '/auth/password/forget'
      path: '/auth/password/forget'
      fullPath: '/auth/password/forget'
      preLoaderRoute: typeof AuthPasswordForgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp/verify': {
      id: '/auth/otp/verify'
      path: '/auth/otp/verify'
      fullPath: '/auth/otp/verify'
      preLoaderRoute: typeof AuthOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Onboarding/vendor-sub-services/two': {
      id: '/Onboarding/vendor-sub-services/two'
      path: '/Onboarding/vendor-sub-services/two'
      fullPath: '/Onboarding/vendor-sub-services/two'
      preLoaderRoute: typeof OnboardingVendorSubServicesTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Onboarding/vendor-sub-services/three': {
      id: '/Onboarding/vendor-sub-services/three'
      path: '/Onboarding/vendor-sub-services/three'
      fullPath: '/Onboarding/vendor-sub-services/three'
      preLoaderRoute: typeof OnboardingVendorSubServicesThreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Onboarding/sub-services/two': {
      id: '/Onboarding/sub-services/two'
      path: '/Onboarding/sub-services/two'
      fullPath: '/Onboarding/sub-services/two'
      preLoaderRoute: typeof OnboardingSubServicesTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Onboarding/sub-services/three': {
      id: '/Onboarding/sub-services/three'
      path: '/Onboarding/sub-services/three'
      fullPath: '/Onboarding/sub-services/three'
      preLoaderRoute: typeof OnboardingSubServicesThreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Onboarding/sub-services/review': {
      id: '/Onboarding/sub-services/review'
      path: '/Onboarding/sub-services/review'
      fullPath: '/Onboarding/sub-services/review'
      preLoaderRoute: typeof OnboardingSubServicesReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Onboarding/sub-services/one': {
      id: '/Onboarding/sub-services/one'
      path: '/Onboarding/sub-services/one'
      fullPath: '/Onboarding/sub-services/one'
      preLoaderRoute: typeof OnboardingSubServicesOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Onboarding/sub-services/four': {
      id: '/Onboarding/sub-services/four'
      path: '/Onboarding/sub-services/four'
      fullPath: '/Onboarding/sub-services/four'
      preLoaderRoute: typeof OnboardingSubServicesFourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Onboarding/sub-services/five': {
      id: '/Onboarding/sub-services/five'
      path: '/Onboarding/sub-services/five'
      fullPath: '/Onboarding/sub-services/five'
      preLoaderRoute: typeof OnboardingSubServicesFiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/event/$eventId/': {
      id: '/vendor/event/$eventId/'
      path: '/vendor/event/$eventId'
      fullPath: '/vendor/event/$eventId'
      preLoaderRoute: typeof VendorEventEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/event/$eventId/proposal': {
      id: '/vendor/event/$eventId/proposal'
      path: '/vendor/event/$eventId/proposal'
      fullPath: '/vendor/event/$eventId/proposal'
      preLoaderRoute: typeof VendorEventEventIdProposalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute,
  AboutRoute: AboutRoute,
  OnboardingServicesRoute: OnboardingServicesRoute,
  OnboardingOnboardingRoute: OnboardingOnboardingRoute,
  OnboardingServiceVendorRoute: OnboardingServiceVendorRoute,
  AccountAddPayoutAccountRoute: AccountAddPayoutAccountRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthSigninRoute: AuthSigninRoute,
  OrganizerAttendeeRoute: OrganizerAttendeeRoute,
  OrganizerLayoutRoute: OrganizerLayoutRoute,
  OrganizerSalesRoute: OrganizerSalesRoute,
  StatusSuccessRoute: StatusSuccessRoute,
  AccountIndexRoute: AccountIndexRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
  VendorIndexRoute: VendorIndexRoute,
  OnboardingSubServicesFiveRoute: OnboardingSubServicesFiveRoute,
  OnboardingSubServicesFourRoute: OnboardingSubServicesFourRoute,
  OnboardingSubServicesOneRoute: OnboardingSubServicesOneRoute,
  OnboardingSubServicesReviewRoute: OnboardingSubServicesReviewRoute,
  OnboardingSubServicesThreeRoute: OnboardingSubServicesThreeRoute,
  OnboardingSubServicesTwoRoute: OnboardingSubServicesTwoRoute,
  OnboardingVendorSubServicesThreeRoute: OnboardingVendorSubServicesThreeRoute,
  OnboardingVendorSubServicesTwoRoute: OnboardingVendorSubServicesTwoRoute,
  AuthOtpVerifyRoute: AuthOtpVerifyRoute,
  AuthPasswordForgetRoute: AuthPasswordForgetRoute,
  AuthPasswordOtpRoute: AuthPasswordOtpRoute,
  VendorProposalProposalIdRoute: VendorProposalProposalIdRoute,
  VendorEventIndexRoute: VendorEventIndexRoute,
  VendorProposalIndexRoute: VendorProposalIndexRoute,
  VendorEventEventIdProposalRoute: VendorEventEventIdProposalRoute,
  VendorEventEventIdIndexRoute: VendorEventEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
